// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zebrahoof_EMR.Data;

#nullable disable

namespace Zebrahoof_EMR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101192736_AddApplicationUserExtendedFields")]
    partial class AddApplicationUserExtendedFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "d12c914d-0bec-47d4-826f-fc97787e3d19",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-physician",
                            ConcurrencyStamp = "eaa790d8-4a99-4afd-8bf5-f8795ca3e750",
                            Name = "Physician",
                            NormalizedName = "PHYSICIAN"
                        },
                        new
                        {
                            Id = "role-nurse",
                            ConcurrencyStamp = "96a9e87a-2b5d-436b-b582-aaf7a0a4bf69",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "role-ma",
                            ConcurrencyStamp = "8f626ab8-2bdc-47ea-8a8d-615dcd7eaf97",
                            Name = "MA",
                            NormalizedName = "MA"
                        },
                        new
                        {
                            Id = "role-billing",
                            ConcurrencyStamp = "fecf3e9f-f94a-4f1a-9a5f-315aa8731fb8",
                            Name = "Billing",
                            NormalizedName = "BILLING"
                        },
                        new
                        {
                            Id = "role-scheduler",
                            ConcurrencyStamp = "3261eab5-0286-413c-9c9a-ea1ad4f24b6b",
                            Name = "Scheduler",
                            NormalizedName = "SCHEDULER"
                        },
                        new
                        {
                            Id = "role-lab",
                            ConcurrencyStamp = "d421a4e0-7dab-4bfc-80ec-2757f6f1c7bd",
                            Name = "Lab",
                            NormalizedName = "LAB"
                        },
                        new
                        {
                            Id = "role-patient",
                            ConcurrencyStamp = "c0ca988d-fec0-4eda-8b87-b8f89b4d9c43",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "Admin",
                            RoleId = "role-admin"
                        },
                        new
                        {
                            UserId = "Physician",
                            RoleId = "role-physician"
                        },
                        new
                        {
                            UserId = "Nurse",
                            RoleId = "role-nurse"
                        },
                        new
                        {
                            UserId = "MA",
                            RoleId = "role-ma"
                        },
                        new
                        {
                            UserId = "Billing",
                            RoleId = "role-billing"
                        },
                        new
                        {
                            UserId = "Scheduler",
                            RoleId = "role-scheduler"
                        },
                        new
                        {
                            UserId = "Lab",
                            RoleId = "role-lab"
                        },
                        new
                        {
                            UserId = "Patient",
                            RoleId = "role-patient"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e12719c-aad1-490c-bee9-9b9d3c3ae9eb",
                            CreatedAt = new DateTime(2026, 1, 1, 19, 27, 35, 796, DateTimeKind.Utc).AddTicks(3888),
                            Department = "Administration",
                            DisplayName = "System Administrator",
                            Email = "admin@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ZEBRAHOOF.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHaG7ieu1XMPsbb7ticZndGfu7UWgYlyhUbu1iM34xre4wxnK8eC6+bIvPy194kMJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "01276d82-75c4-4277-a97e-1418d7ca64dd",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "Physician",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "77467bbe-969d-4158-a6f1-1ebb00746245",
                            CreatedAt = new DateTime(2026, 1, 1, 19, 27, 35, 847, DateTimeKind.Utc).AddTicks(374),
                            Department = "Clinical",
                            DisplayName = "Attending Physician",
                            Email = "physician@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PHYSICIAN@ZEBRAHOOF.COM",
                            NormalizedUserName = "PHYSICIAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPxh8GOk/GMHeyRrs1KVR5xwdQel7J8k6+wMJINHps1ulPp31+fZJ9CR+fhYBw/IoQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b9e6cbf6-963e-4af4-a255-b46cbdd13f37",
                            TwoFactorEnabled = false,
                            UserName = "Physician"
                        },
                        new
                        {
                            Id = "Nurse",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "51fd6800-eaca-4384-a451-b7cadee43a98",
                            CreatedAt = new DateTime(2026, 1, 1, 19, 27, 35, 897, DateTimeKind.Utc).AddTicks(1867),
                            Department = "Clinical",
                            DisplayName = "Charge Nurse",
                            Email = "nurse@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE@ZEBRAHOOF.COM",
                            NormalizedUserName = "NURSE",
                            PasswordHash = "AQAAAAIAAYagAAAAEBykJfKuEB0Cks/qtyCL7jRFUekYIVjCQsky0yWAFSdVx0JrOsDDOrdPwNCjZgqfwQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4c1e648d-229e-46e0-b8e4-6e4b1b3ad100",
                            TwoFactorEnabled = false,
                            UserName = "Nurse"
                        },
                        new
                        {
                            Id = "MA",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "128a7ece-b689-4c7f-8269-1cffc03343fa",
                            CreatedAt = new DateTime(2026, 1, 1, 19, 27, 35, 947, DateTimeKind.Utc).AddTicks(8882),
                            Department = "Clinical Support",
                            DisplayName = "Medical Assistant",
                            Email = "ma@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MA@ZEBRAHOOF.COM",
                            NormalizedUserName = "MA",
                            PasswordHash = "AQAAAAIAAYagAAAAEAyeoZSklz8Ow+Ivr3zdOlplX9dc6Yvj0cOELg6WkG88dlLtklP9zwVK4VAvP//B6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5fcef561-99e5-4b34-9d14-eb058cfb8bd7",
                            TwoFactorEnabled = false,
                            UserName = "MA"
                        },
                        new
                        {
                            Id = "Billing",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e17a1930-cbec-404a-98e7-3c85ff604f63",
                            CreatedAt = new DateTime(2026, 1, 1, 19, 27, 35, 999, DateTimeKind.Utc).AddTicks(9328),
                            Department = "Revenue Cycle",
                            DisplayName = "Billing Specialist",
                            Email = "billing@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BILLING@ZEBRAHOOF.COM",
                            NormalizedUserName = "BILLING",
                            PasswordHash = "AQAAAAIAAYagAAAAEFLWpL+bxzDIVbIbRlXaja6JDvqC1MRtIwLOjW3s+MneFq/4eo2IVl0tdRrTe8+uBA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7cb0732-b9a0-4bae-90c7-d038e21a2216",
                            TwoFactorEnabled = false,
                            UserName = "Billing"
                        },
                        new
                        {
                            Id = "Scheduler",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00f891c4-eb3c-4e30-ac2f-5274327313ce",
                            CreatedAt = new DateTime(2026, 1, 1, 19, 27, 36, 51, DateTimeKind.Utc).AddTicks(3660),
                            Department = "Operations",
                            DisplayName = "Scheduling Coordinator",
                            Email = "scheduler@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SCHEDULER@ZEBRAHOOF.COM",
                            NormalizedUserName = "SCHEDULER",
                            PasswordHash = "AQAAAAIAAYagAAAAEC/HdRlmyhMx8F/oZcM+0zDG0SEncns9gQ1AW69IDuqj26lwAHT1hSIvDYZjRPOUkg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "929e923f-a152-4525-9a03-6cba23ca4d37",
                            TwoFactorEnabled = false,
                            UserName = "Scheduler"
                        },
                        new
                        {
                            Id = "Lab",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9269baa-dfcd-41f3-9665-bd15137b1d3e",
                            CreatedAt = new DateTime(2026, 1, 1, 19, 27, 36, 103, DateTimeKind.Utc).AddTicks(6882),
                            Department = "Diagnostics",
                            DisplayName = "Lab Technician",
                            Email = "lab@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LAB@ZEBRAHOOF.COM",
                            NormalizedUserName = "LAB",
                            PasswordHash = "AQAAAAIAAYagAAAAEFysa7VKxG9pf4Ua5wwIF5j4vZXUynCSGEogfcsX6l1xc9My7LQoEkoCGBBlfq2v2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1251368e-7c93-415b-ae1f-d4c137bf2cbb",
                            TwoFactorEnabled = false,
                            UserName = "Lab"
                        },
                        new
                        {
                            Id = "Patient",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f00d42a-ad2e-42cf-8c8d-b25bfd10e2b2",
                            CreatedAt = new DateTime(2026, 1, 1, 19, 27, 36, 155, DateTimeKind.Utc).AddTicks(1998),
                            Department = "Patient Portal",
                            DisplayName = "Sample Patient",
                            Email = "patient@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT@ZEBRAHOOF.COM",
                            NormalizedUserName = "PATIENT",
                            PasswordHash = "AQAAAAIAAYagAAAAEIO7/gC2XsDWiMS6ENNbKS99Gpy91Qywo646HzNfq1Y2fdY2H2lrmSUoGi0rS47C4g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4932699b-e23a-4d78-887e-28a96d70d1a5",
                            TwoFactorEnabled = false,
                            UserName = "Patient"
                        });
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "DateTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.ClinicalTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo", "Status");

                    b.ToTable("ClinicalTasks");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("To");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alerts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("TEXT");

                    b.Property<string>("MRN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MRN")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            UserId = "Admin",
                            Department = "Administration",
                            DisplayName = "System Administrator"
                        },
                        new
                        {
                            UserId = "Physician",
                            Department = "Clinical",
                            DisplayName = "Attending Physician"
                        },
                        new
                        {
                            UserId = "Nurse",
                            Department = "Clinical",
                            DisplayName = "Charge Nurse"
                        },
                        new
                        {
                            UserId = "MA",
                            Department = "Clinical Support",
                            DisplayName = "Medical Assistant"
                        },
                        new
                        {
                            UserId = "Billing",
                            Department = "Revenue Cycle",
                            DisplayName = "Billing Specialist"
                        },
                        new
                        {
                            UserId = "Scheduler",
                            Department = "Operations",
                            DisplayName = "Scheduling Coordinator"
                        },
                        new
                        {
                            UserId = "Lab",
                            Department = "Diagnostics",
                            DisplayName = "Lab Technician"
                        },
                        new
                        {
                            UserId = "Patient",
                            Department = "Patient Portal",
                            DisplayName = "Sample Patient"
                        });
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.AuditLog", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserProfile", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Zebrahoof_EMR.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserSession", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
