// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zebrahoof_EMR.Data;

#nullable disable

namespace Zebrahoof_EMR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101214856_AddSessionColumns")]
    partial class AddSessionColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "3b27ed8e-8f68-427a-8743-80597dc55b13",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-physician",
                            ConcurrencyStamp = "97b2223d-a8ce-40d9-b88c-9fa05660295c",
                            Name = "Physician",
                            NormalizedName = "PHYSICIAN"
                        },
                        new
                        {
                            Id = "role-nurse",
                            ConcurrencyStamp = "fd147590-1c67-40ce-a998-17c5495dfdab",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "role-ma",
                            ConcurrencyStamp = "79da496f-4b50-443d-9883-067c24feeca3",
                            Name = "MA",
                            NormalizedName = "MA"
                        },
                        new
                        {
                            Id = "role-billing",
                            ConcurrencyStamp = "db8fac39-48ee-415e-b5bf-af28ae661a73",
                            Name = "Billing",
                            NormalizedName = "BILLING"
                        },
                        new
                        {
                            Id = "role-scheduler",
                            ConcurrencyStamp = "a15a001c-5089-4445-8cbf-7782e0211ac2",
                            Name = "Scheduler",
                            NormalizedName = "SCHEDULER"
                        },
                        new
                        {
                            Id = "role-lab",
                            ConcurrencyStamp = "69e0c516-8628-4f0b-a555-fc70b6bd94e7",
                            Name = "Lab",
                            NormalizedName = "LAB"
                        },
                        new
                        {
                            Id = "role-patient",
                            ConcurrencyStamp = "f1127591-9642-4d19-804f-f36029890be8",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "Admin",
                            RoleId = "role-admin"
                        },
                        new
                        {
                            UserId = "Physician",
                            RoleId = "role-physician"
                        },
                        new
                        {
                            UserId = "Nurse",
                            RoleId = "role-nurse"
                        },
                        new
                        {
                            UserId = "MA",
                            RoleId = "role-ma"
                        },
                        new
                        {
                            UserId = "Billing",
                            RoleId = "role-billing"
                        },
                        new
                        {
                            UserId = "Scheduler",
                            RoleId = "role-scheduler"
                        },
                        new
                        {
                            UserId = "Lab",
                            RoleId = "role-lab"
                        },
                        new
                        {
                            UserId = "Patient",
                            RoleId = "role-patient"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30f520df-4c46-4740-b157-12bbddf7b708",
                            CreatedAt = new DateTime(2026, 1, 1, 21, 48, 55, 944, DateTimeKind.Utc).AddTicks(6055),
                            Department = "Administration",
                            DisplayName = "System Administrator",
                            Email = "admin@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ZEBRAHOOF.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEF4TKmuiEkSv6Juqp6Te03I6wg14E9sN1ebshFfUTdwFE6EDOj/7/+C+Tb19Epx2vQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "75d71a3e-c851-41e7-875a-12c6b87dd1b4",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "Physician",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "02502d23-1cc5-47b8-bb79-17901a378db4",
                            CreatedAt = new DateTime(2026, 1, 1, 21, 48, 55, 995, DateTimeKind.Utc).AddTicks(811),
                            Department = "Clinical",
                            DisplayName = "Attending Physician",
                            Email = "physician@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PHYSICIAN@ZEBRAHOOF.COM",
                            NormalizedUserName = "PHYSICIAN",
                            PasswordHash = "AQAAAAIAAYagAAAAECVfSu0X3rZj7SaiW27/itE4XyxT11DykvGpTDi4CJL6CK4SWG1k3A3otONX7oD+DQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bd850f7d-ada1-4d8e-bd42-09c67fe1a92c",
                            TwoFactorEnabled = false,
                            UserName = "Physician"
                        },
                        new
                        {
                            Id = "Nurse",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "747b23e8-90e4-4a7e-9c16-c28eaa8017d9",
                            CreatedAt = new DateTime(2026, 1, 1, 21, 48, 56, 45, DateTimeKind.Utc).AddTicks(8252),
                            Department = "Clinical",
                            DisplayName = "Charge Nurse",
                            Email = "nurse@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE@ZEBRAHOOF.COM",
                            NormalizedUserName = "NURSE",
                            PasswordHash = "AQAAAAIAAYagAAAAEBf19gfCS6pKNyiutYuMulYHRtG5QsDD/gbPp6u48GOS1ZOJjJ+dsgqZvBDCEdPXMQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d5b98e88-4748-4a56-8ea1-419aae328411",
                            TwoFactorEnabled = false,
                            UserName = "Nurse"
                        },
                        new
                        {
                            Id = "MA",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f99b1561-340f-4285-bfd3-9eba5e75c26e",
                            CreatedAt = new DateTime(2026, 1, 1, 21, 48, 56, 95, DateTimeKind.Utc).AddTicks(1430),
                            Department = "Clinical Support",
                            DisplayName = "Medical Assistant",
                            Email = "ma@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MA@ZEBRAHOOF.COM",
                            NormalizedUserName = "MA",
                            PasswordHash = "AQAAAAIAAYagAAAAEA0IsmfkvCCiXudfYN8ce/ivJAVMoHZuw5+MPd+vPu/pITLOP8iRnb0bbpwbkFNzSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb700cf6-34e1-453d-bf73-21e01be60089",
                            TwoFactorEnabled = false,
                            UserName = "MA"
                        },
                        new
                        {
                            Id = "Billing",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d8bffa5b-7407-4799-af04-02c68bf63a8b",
                            CreatedAt = new DateTime(2026, 1, 1, 21, 48, 56, 145, DateTimeKind.Utc).AddTicks(4879),
                            Department = "Revenue Cycle",
                            DisplayName = "Billing Specialist",
                            Email = "billing@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BILLING@ZEBRAHOOF.COM",
                            NormalizedUserName = "BILLING",
                            PasswordHash = "AQAAAAIAAYagAAAAEInbsVSkHBmR6tNTte+FbtBfSjzE34dQ9StxKHJcmDf1HUDcH9KxB6GSNxaUhJJInQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e712454b-e66a-469f-8f56-9ae104036ab0",
                            TwoFactorEnabled = false,
                            UserName = "Billing"
                        },
                        new
                        {
                            Id = "Scheduler",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a02bf90-0638-4224-8357-054772d46dff",
                            CreatedAt = new DateTime(2026, 1, 1, 21, 48, 56, 195, DateTimeKind.Utc).AddTicks(9295),
                            Department = "Operations",
                            DisplayName = "Scheduling Coordinator",
                            Email = "scheduler@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SCHEDULER@ZEBRAHOOF.COM",
                            NormalizedUserName = "SCHEDULER",
                            PasswordHash = "AQAAAAIAAYagAAAAELi3PVx8f1YMZGuJkCBuJn8cVx+ORmcsePuCPfRnP+qRQsP3NHHxXPE1+FPdpW4xtg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6c22b23d-fc56-451e-9c61-56c52ea2b5f6",
                            TwoFactorEnabled = false,
                            UserName = "Scheduler"
                        },
                        new
                        {
                            Id = "Lab",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05047eec-d987-48d4-8ba4-f146245b6689",
                            CreatedAt = new DateTime(2026, 1, 1, 21, 48, 56, 247, DateTimeKind.Utc).AddTicks(1549),
                            Department = "Diagnostics",
                            DisplayName = "Lab Technician",
                            Email = "lab@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LAB@ZEBRAHOOF.COM",
                            NormalizedUserName = "LAB",
                            PasswordHash = "AQAAAAIAAYagAAAAEGJL1u7V9Hk8yMXF/jQVRd/Dkv5+jXvL1z5THYPC618CwvpL6RSri3EHrCtZI2RW5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fff7c015-9d48-4d7b-aed5-46391f0bb228",
                            TwoFactorEnabled = false,
                            UserName = "Lab"
                        },
                        new
                        {
                            Id = "Patient",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "041f2fb4-e7d6-477c-8a64-4c05692bf8b5",
                            CreatedAt = new DateTime(2026, 1, 1, 21, 48, 56, 297, DateTimeKind.Utc).AddTicks(4155),
                            Department = "Patient Portal",
                            DisplayName = "Sample Patient",
                            Email = "patient@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT@ZEBRAHOOF.COM",
                            NormalizedUserName = "PATIENT",
                            PasswordHash = "AQAAAAIAAYagAAAAEOl6LI3TqPwK53hfHIUKfKg/ZJl4qAtTbWUx8oLiHxLbzHZPjKnb0fSN9fMqw1mqgA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d55d0218-065d-46ce-b3af-1155a4ff9009",
                            TwoFactorEnabled = false,
                            UserName = "Patient"
                        });
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "DateTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.ClinicalTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo", "Status");

                    b.ToTable("ClinicalTasks");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("To");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alerts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("TEXT");

                    b.Property<string>("MRN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MRN")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            UserId = "Admin",
                            Department = "Administration",
                            DisplayName = "System Administrator"
                        },
                        new
                        {
                            UserId = "Physician",
                            Department = "Clinical",
                            DisplayName = "Attending Physician"
                        },
                        new
                        {
                            UserId = "Nurse",
                            Department = "Clinical",
                            DisplayName = "Charge Nurse"
                        },
                        new
                        {
                            UserId = "MA",
                            Department = "Clinical Support",
                            DisplayName = "Medical Assistant"
                        },
                        new
                        {
                            UserId = "Billing",
                            Department = "Revenue Cycle",
                            DisplayName = "Billing Specialist"
                        },
                        new
                        {
                            UserId = "Scheduler",
                            Department = "Operations",
                            DisplayName = "Scheduling Coordinator"
                        },
                        new
                        {
                            UserId = "Lab",
                            Department = "Diagnostics",
                            DisplayName = "Lab Technician"
                        },
                        new
                        {
                            UserId = "Patient",
                            Department = "Patient Portal",
                            DisplayName = "Sample Patient"
                        });
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdleTimeoutMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.AuditLog", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserProfile", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Zebrahoof_EMR.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserSession", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
