// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zebrahoof_EMR.Data;

#nullable disable

namespace Zebrahoof_EMR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109053031_AddStickyNotes")]
    partial class AddStickyNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "11ed5170-0e22-4423-a2cd-5b3d55d8abe1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-physician",
                            ConcurrencyStamp = "38e1e969-9e13-4ea0-95fd-b51a3c6db920",
                            Name = "Physician",
                            NormalizedName = "PHYSICIAN"
                        },
                        new
                        {
                            Id = "role-nurse",
                            ConcurrencyStamp = "b9eba352-4820-4048-8757-e6763b3ebe4c",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "role-ma",
                            ConcurrencyStamp = "f10ae219-4c14-4343-8ce3-a1f6ec29fa76",
                            Name = "MA",
                            NormalizedName = "MA"
                        },
                        new
                        {
                            Id = "role-billing",
                            ConcurrencyStamp = "f3718185-592b-4e0b-9bdc-589e2831243e",
                            Name = "Billing",
                            NormalizedName = "BILLING"
                        },
                        new
                        {
                            Id = "role-scheduler",
                            ConcurrencyStamp = "c9836d02-6517-4c41-a079-aa929feb4024",
                            Name = "Scheduler",
                            NormalizedName = "SCHEDULER"
                        },
                        new
                        {
                            Id = "role-lab",
                            ConcurrencyStamp = "b4d4d356-2019-4192-bdb7-798d3eb85c5f",
                            Name = "Lab",
                            NormalizedName = "LAB"
                        },
                        new
                        {
                            Id = "role-patient",
                            ConcurrencyStamp = "8cff3eb3-569f-4572-8b85-9197c22787cd",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "Admin",
                            RoleId = "role-admin"
                        },
                        new
                        {
                            UserId = "Physician",
                            RoleId = "role-physician"
                        },
                        new
                        {
                            UserId = "Nurse",
                            RoleId = "role-nurse"
                        },
                        new
                        {
                            UserId = "MA",
                            RoleId = "role-ma"
                        },
                        new
                        {
                            UserId = "Billing",
                            RoleId = "role-billing"
                        },
                        new
                        {
                            UserId = "Scheduler",
                            RoleId = "role-scheduler"
                        },
                        new
                        {
                            UserId = "Lab",
                            RoleId = "role-lab"
                        },
                        new
                        {
                            UserId = "Patient",
                            RoleId = "role-patient"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c383c23-a550-4d5e-9104-ba4d3ce3c415",
                            CreatedAt = new DateTime(2026, 1, 9, 5, 30, 31, 28, DateTimeKind.Utc).AddTicks(759),
                            Department = "Administration",
                            DisplayName = "System Administrator",
                            Email = "admin@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ZEBRAHOOF.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEN1fCQ0jHgpzJQeDZVFYjEX9/QJz0j7KymsQ8AXOGOT/Z6z6uWsUfujjKspedWiuIQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb09ebb7-7c42-4429-8b3b-a03717a0a836",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "Physician",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6bf276c0-eaf4-441d-bd45-6922b548af08",
                            CreatedAt = new DateTime(2026, 1, 9, 5, 30, 31, 77, DateTimeKind.Utc).AddTicks(3908),
                            Department = "Clinical",
                            DisplayName = "Attending Physician",
                            Email = "physician@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PHYSICIAN@ZEBRAHOOF.COM",
                            NormalizedUserName = "PHYSICIAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEIXv8kJxlEB31Huy5/whAXsN5wCF7OEpF7tF5hAZ7byWz9kbLuf4hQknsBp+u3WZ/A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1485305-e4c7-44c9-89e1-d860fe43bbc6",
                            TwoFactorEnabled = false,
                            UserName = "Physician"
                        },
                        new
                        {
                            Id = "Nurse",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "25782c69-3001-4e14-9a67-91d45b396ec2",
                            CreatedAt = new DateTime(2026, 1, 9, 5, 30, 31, 127, DateTimeKind.Utc).AddTicks(1322),
                            Department = "Clinical",
                            DisplayName = "Charge Nurse",
                            Email = "nurse@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE@ZEBRAHOOF.COM",
                            NormalizedUserName = "NURSE",
                            PasswordHash = "AQAAAAIAAYagAAAAEE5jkpAuidPDnz/lwyZsNHjOj0fp3TGaI9BeAzEbDa7229beYGWY/bX8waWLCEhBtg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "70486bd5-f853-4b80-902a-d3149b03133f",
                            TwoFactorEnabled = false,
                            UserName = "Nurse"
                        },
                        new
                        {
                            Id = "MA",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a24118f8-f1c5-4900-823b-5f46c856fb1d",
                            CreatedAt = new DateTime(2026, 1, 9, 5, 30, 31, 176, DateTimeKind.Utc).AddTicks(7159),
                            Department = "Clinical Support",
                            DisplayName = "Medical Assistant",
                            Email = "ma@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MA@ZEBRAHOOF.COM",
                            NormalizedUserName = "MA",
                            PasswordHash = "AQAAAAIAAYagAAAAECPDXxN0+tCo2g1Kv5BnAZYWUxoP5K80BZxvn8biPLjybpXl11PhD/ug1PxdTZ/PFA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c34bed71-9b7e-4438-9767-d0b125020461",
                            TwoFactorEnabled = false,
                            UserName = "MA"
                        },
                        new
                        {
                            Id = "Billing",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "670abb40-ecd4-454d-bb10-7d32626e8574",
                            CreatedAt = new DateTime(2026, 1, 9, 5, 30, 31, 229, DateTimeKind.Utc).AddTicks(5708),
                            Department = "Revenue Cycle",
                            DisplayName = "Billing Specialist",
                            Email = "billing@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BILLING@ZEBRAHOOF.COM",
                            NormalizedUserName = "BILLING",
                            PasswordHash = "AQAAAAIAAYagAAAAEMQMajWScOiK52mNo4qimQELUz75UQN6tY5Njy1s4NTtQIJHUz7KmabB7VN6lsHSlA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5c529c59-8491-4d21-92ad-32402c1287c5",
                            TwoFactorEnabled = false,
                            UserName = "Billing"
                        },
                        new
                        {
                            Id = "Scheduler",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df5661ab-9cb7-4e4e-947b-51d51a2bc31f",
                            CreatedAt = new DateTime(2026, 1, 9, 5, 30, 31, 284, DateTimeKind.Utc).AddTicks(87),
                            Department = "Operations",
                            DisplayName = "Scheduling Coordinator",
                            Email = "scheduler@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SCHEDULER@ZEBRAHOOF.COM",
                            NormalizedUserName = "SCHEDULER",
                            PasswordHash = "AQAAAAIAAYagAAAAEMflWiplso9dF4C3mGcADbD0EgtCpAldr5t143OaEeq2xyd1EvbB7GPlv/jvUkA5IQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "12c532ca-1037-4256-ae0a-d179bcc836eb",
                            TwoFactorEnabled = false,
                            UserName = "Scheduler"
                        },
                        new
                        {
                            Id = "Lab",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a2bb0474-0b5e-44d2-b828-e53593d36872",
                            CreatedAt = new DateTime(2026, 1, 9, 5, 30, 31, 337, DateTimeKind.Utc).AddTicks(5569),
                            Department = "Diagnostics",
                            DisplayName = "Lab Technician",
                            Email = "lab@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LAB@ZEBRAHOOF.COM",
                            NormalizedUserName = "LAB",
                            PasswordHash = "AQAAAAIAAYagAAAAEAlsqe4R2jut1l1IhaELNWURAUgB8O5SAfxB6iccY2RlcShRWVg81tV5us2pWYEa9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "994f99b6-f124-4df4-905b-f7ca8e6746b7",
                            TwoFactorEnabled = false,
                            UserName = "Lab"
                        },
                        new
                        {
                            Id = "Patient",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1887617e-6bfd-4908-9ae9-ae5f7a8bd039",
                            CreatedAt = new DateTime(2026, 1, 9, 5, 30, 31, 387, DateTimeKind.Utc).AddTicks(7913),
                            Department = "Patient Portal",
                            DisplayName = "Sample Patient",
                            Email = "patient@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT@ZEBRAHOOF.COM",
                            NormalizedUserName = "PATIENT",
                            PasswordHash = "AQAAAAIAAYagAAAAENDdgDXsovgj0dC14aXhhcyi7e3M3kkW4MZ+NWM2BYPMEPVqy0Jn4FteujldKBAGsw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3ea1fde6-d7b3-4231-ba89-50557f78839a",
                            TwoFactorEnabled = false,
                            UserName = "Patient"
                        });
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "DateTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.ClinicalTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo", "Status");

                    b.ToTable("ClinicalTasks");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("To");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alerts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("TEXT");

                    b.Property<string>("MRN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MRN")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.StickyNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StickyNotes");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            UserId = "Admin",
                            Department = "Administration",
                            DisplayName = "System Administrator"
                        },
                        new
                        {
                            UserId = "Physician",
                            Department = "Clinical",
                            DisplayName = "Attending Physician"
                        },
                        new
                        {
                            UserId = "Nurse",
                            Department = "Clinical",
                            DisplayName = "Charge Nurse"
                        },
                        new
                        {
                            UserId = "MA",
                            Department = "Clinical Support",
                            DisplayName = "Medical Assistant"
                        },
                        new
                        {
                            UserId = "Billing",
                            Department = "Revenue Cycle",
                            DisplayName = "Billing Specialist"
                        },
                        new
                        {
                            UserId = "Scheduler",
                            Department = "Operations",
                            DisplayName = "Scheduling Coordinator"
                        },
                        new
                        {
                            UserId = "Lab",
                            Department = "Diagnostics",
                            DisplayName = "Lab Technician"
                        },
                        new
                        {
                            UserId = "Patient",
                            Department = "Patient Portal",
                            DisplayName = "Sample Patient"
                        });
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdleTimeoutMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.AuditLog", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Document", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserProfile", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Zebrahoof_EMR.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserSession", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
