// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zebrahoof_EMR.Data;

#nullable disable

namespace Zebrahoof_EMR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419232029_AddEncounterMessages")]
    partial class AddEncounterMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "8f29bbc9-4a43-48cc-a4d3-a7f64ecb0041",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-physician",
                            ConcurrencyStamp = "ca262c94-1cb9-4bff-9a9b-f88ea8528516",
                            Name = "Physician",
                            NormalizedName = "PHYSICIAN"
                        },
                        new
                        {
                            Id = "role-nurse",
                            ConcurrencyStamp = "2c1f032b-d5e0-4b06-8ec5-620a05855aea",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "role-ma",
                            ConcurrencyStamp = "c8fd2a79-45f2-4076-affa-144d3485612f",
                            Name = "MA",
                            NormalizedName = "MA"
                        },
                        new
                        {
                            Id = "role-billing",
                            ConcurrencyStamp = "119991bb-da87-4464-9e89-daecd9afe132",
                            Name = "Billing",
                            NormalizedName = "BILLING"
                        },
                        new
                        {
                            Id = "role-scheduler",
                            ConcurrencyStamp = "c36c93a9-f674-4347-9f43-071b1d7330d0",
                            Name = "Scheduler",
                            NormalizedName = "SCHEDULER"
                        },
                        new
                        {
                            Id = "role-lab",
                            ConcurrencyStamp = "401ab706-701c-45df-a8f4-53ddde663c4d",
                            Name = "Lab",
                            NormalizedName = "LAB"
                        },
                        new
                        {
                            Id = "role-patient",
                            ConcurrencyStamp = "14ec72f0-3598-47e3-8221-b4226c7e5fdd",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "Admin",
                            RoleId = "role-admin"
                        },
                        new
                        {
                            UserId = "Physician",
                            RoleId = "role-physician"
                        },
                        new
                        {
                            UserId = "Nurse",
                            RoleId = "role-nurse"
                        },
                        new
                        {
                            UserId = "MA",
                            RoleId = "role-ma"
                        },
                        new
                        {
                            UserId = "Billing",
                            RoleId = "role-billing"
                        },
                        new
                        {
                            UserId = "Scheduler",
                            RoleId = "role-scheduler"
                        },
                        new
                        {
                            UserId = "Lab",
                            RoleId = "role-lab"
                        },
                        new
                        {
                            UserId = "Patient",
                            RoleId = "role-patient"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Allergen")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OnsetDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reaction")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "35a9c835-5446-413c-944a-0b9cc6b2f81f",
                            CreatedAt = new DateTime(2026, 4, 19, 23, 20, 28, 877, DateTimeKind.Utc).AddTicks(9119),
                            Department = "Administration",
                            DisplayName = "System Administrator",
                            Email = "admin@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ZEBRAHOOF.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEKzu6xEoPoDkI9pcgSLNrHCeUGCty28+HkKChDZ0n8NyvflxWJwc+1e3EnwpAl5Qvw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb16ff86-7987-4fc0-9173-34d49aa2f456",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "Physician",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa9adfdc-954a-4e1b-a0dc-f3d6cc116932",
                            CreatedAt = new DateTime(2026, 4, 19, 23, 20, 28, 928, DateTimeKind.Utc).AddTicks(6665),
                            Department = "Clinical",
                            DisplayName = "Attending Physician",
                            Email = "physician@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PHYSICIAN@ZEBRAHOOF.COM",
                            NormalizedUserName = "PHYSICIAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEL9+hOGTQXiveehArWts8z/WmrCUHBjg8JKQewm2t5TU7wTwmHtVWi78YmqDmmx5jg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "01523c76-8873-4d27-82c2-3d909b2a97b7",
                            TwoFactorEnabled = false,
                            UserName = "Physician"
                        },
                        new
                        {
                            Id = "Nurse",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a89fdd1f-c12f-4b82-bb39-f886ed309500",
                            CreatedAt = new DateTime(2026, 4, 19, 23, 20, 28, 980, DateTimeKind.Utc).AddTicks(5538),
                            Department = "Clinical",
                            DisplayName = "Charge Nurse",
                            Email = "nurse@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NURSE@ZEBRAHOOF.COM",
                            NormalizedUserName = "NURSE",
                            PasswordHash = "AQAAAAIAAYagAAAAEI3Mq27fq2WLl/Iw0JFV95NBDmi0SSYO6IubUBlNW9eNBC/3nwa7K341ObDug2tILw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "536b45bf-d0d0-43e1-8f2b-addc1a34a6bc",
                            TwoFactorEnabled = false,
                            UserName = "Nurse"
                        },
                        new
                        {
                            Id = "MA",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "66c6394a-8b6d-4c4c-9398-ed1cc7fd10a2",
                            CreatedAt = new DateTime(2026, 4, 19, 23, 20, 29, 34, DateTimeKind.Utc).AddTicks(5633),
                            Department = "Clinical Support",
                            DisplayName = "Medical Assistant",
                            Email = "ma@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MA@ZEBRAHOOF.COM",
                            NormalizedUserName = "MA",
                            PasswordHash = "AQAAAAIAAYagAAAAEPqhXyH8Q104uLy4XpGk//OlezTIpRFuH8EzlBvzFWcqDbLk1D7osAFubjm7WRcfWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "86a097a9-4932-4a38-95c2-b1b050fdbe83",
                            TwoFactorEnabled = false,
                            UserName = "MA"
                        },
                        new
                        {
                            Id = "Billing",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e49bc192-c832-4250-a9b1-150c7d6986e7",
                            CreatedAt = new DateTime(2026, 4, 19, 23, 20, 29, 86, DateTimeKind.Utc).AddTicks(7991),
                            Department = "Revenue Cycle",
                            DisplayName = "Billing Specialist",
                            Email = "billing@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BILLING@ZEBRAHOOF.COM",
                            NormalizedUserName = "BILLING",
                            PasswordHash = "AQAAAAIAAYagAAAAEJGVw7Xx85KCB8pmwzMw3UGOLm6XiWmvgvq/Db+6Z0jDgYdg8zAsP48pCVEas7Q1dg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47c037ab-6f49-4392-8ab9-d1e0c27424e8",
                            TwoFactorEnabled = false,
                            UserName = "Billing"
                        },
                        new
                        {
                            Id = "Scheduler",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46b32db7-ae35-43db-afbf-466c8984c35b",
                            CreatedAt = new DateTime(2026, 4, 19, 23, 20, 29, 138, DateTimeKind.Utc).AddTicks(5028),
                            Department = "Operations",
                            DisplayName = "Scheduling Coordinator",
                            Email = "scheduler@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SCHEDULER@ZEBRAHOOF.COM",
                            NormalizedUserName = "SCHEDULER",
                            PasswordHash = "AQAAAAIAAYagAAAAEJFJflrcMdY1vkpFoQA33xmcllJgT39OzAcAFGpuWJjHiRYAi1oMoVwI96qjV03rBA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5617e609-e4c6-4465-8ed7-ccbd9de8a8cc",
                            TwoFactorEnabled = false,
                            UserName = "Scheduler"
                        },
                        new
                        {
                            Id = "Lab",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a9574389-f46a-4788-b612-65c28599786a",
                            CreatedAt = new DateTime(2026, 4, 19, 23, 20, 29, 189, DateTimeKind.Utc).AddTicks(5167),
                            Department = "Diagnostics",
                            DisplayName = "Lab Technician",
                            Email = "lab@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LAB@ZEBRAHOOF.COM",
                            NormalizedUserName = "LAB",
                            PasswordHash = "AQAAAAIAAYagAAAAEBxoLfcgo+cT8BqayEkA+bwRrrK6yRghClmFV+0opFu8DGPhBSnwEg58n+C64EGrjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "95633fe2-5781-4106-8d3b-e454a21f2f1c",
                            TwoFactorEnabled = false,
                            UserName = "Lab"
                        },
                        new
                        {
                            Id = "Patient",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a8942ce4-a0d7-4e0a-b1e9-d14984259022",
                            CreatedAt = new DateTime(2026, 4, 19, 23, 20, 29, 241, DateTimeKind.Utc).AddTicks(345),
                            Department = "Patient Portal",
                            DisplayName = "Sample Patient",
                            Email = "patient@zebrahoof.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT@ZEBRAHOOF.COM",
                            NormalizedUserName = "PATIENT",
                            PasswordHash = "AQAAAAIAAYagAAAAEIiVuLXGTqLsCi3QkjlOZFPTP5kSQ3WhzrqWPHt4MWOu9NbrI4qS3wzIlxYzUYAXSw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31df86ac-abe3-4304-b458-e666382f8ca2",
                            TwoFactorEnabled = false,
                            UserName = "Patient"
                        });
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "DateTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.ClinicalTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo", "Status");

                    b.ToTable("ClinicalTasks");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.EncounterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrokResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludedHistory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserInput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "CreatedAt");

                    b.ToTable("EncounterMessages");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DaysSupply")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHighRisk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLongTerm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pharmacy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prescriber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RefillsRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("To");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alerts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("TEXT");

                    b.Property<string>("MRN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MRN")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.PatientStickyNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PatientId")
                        .IsUnique();

                    b.ToTable("PatientStickyNotes");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IcdCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OnsetDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.StickyNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StickyNotes");
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            UserId = "Admin",
                            Department = "Administration",
                            DisplayName = "System Administrator"
                        },
                        new
                        {
                            UserId = "Physician",
                            Department = "Clinical",
                            DisplayName = "Attending Physician"
                        },
                        new
                        {
                            UserId = "Nurse",
                            Department = "Clinical",
                            DisplayName = "Charge Nurse"
                        },
                        new
                        {
                            UserId = "MA",
                            Department = "Clinical Support",
                            DisplayName = "Medical Assistant"
                        },
                        new
                        {
                            UserId = "Billing",
                            Department = "Revenue Cycle",
                            DisplayName = "Billing Specialist"
                        },
                        new
                        {
                            UserId = "Scheduler",
                            Department = "Operations",
                            DisplayName = "Scheduling Coordinator"
                        },
                        new
                        {
                            UserId = "Lab",
                            Department = "Diagnostics",
                            DisplayName = "Lab Technician"
                        },
                        new
                        {
                            UserId = "Patient",
                            Department = "Patient Portal",
                            DisplayName = "Sample Patient"
                        });
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdleTimeoutMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.AuditLog", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserProfile", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Zebrahoof_EMR.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zebrahoof_EMR.Models.UserSession", b =>
                {
                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zebrahoof_EMR.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
